cadenza/models.py
from . import db

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('product_id',db.Integer,db.ForeignKey('products.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'product_id') )

class Product(db.Model):

    __tablename__='products'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    sub_headline = db.Column(db.String(64), nullable=False, default='Coming Soon')
    category = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(500), nullable=False, default='Coming Soon')
    price = db.Column(db.Float, nullable=False)
    size = db.Column(db.Integer, nullable=False,  default=0)
    scent_id = db.Column(db.Integer, db.ForeignKey('scents.id'))
    image_url = db.Column(db.String(200), nullable=False,  default=0)
    scent=db.relationship('Scent', backref='scent',lazy=True)
    

    def __repr__(self):
        str = 'ID: {}, Name: {}, Category: {}, Description: {} Price: {}, Size: {}, Scent: {}, Img URL: {} \n'
        str = str.format(self.id, self.name, self.category, self.description, self.price, self.size, self.scent_id, self.image_url)
        return str
    
class Order(db.Model):

    __tablename__='orders'

    id = db.Column(db.Integer, primary_key=True)
    payment_status = db.Column(db.Boolean, default = False)
    date = db.Column(db.DateTime)
    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    address = db.Column(db.String(64))
    city = db.Column(db.String(64))
    state = db.Column(db.String(64))
    post_code = db.Column(db.String(64))
    products = db.relationship("Product", secondary=orderdetails, backref="orders")
    
    def __repr__(self):
        str = 'ID: {}, Date: {}, First Name: {}, Last Name: {}, Email" {}, Phone: {}, Address: {}\n'
        str = str.format(self.id, self.date, self.first_name, self.last_name, self.email, self.phone, self.address)
        return str


class Scent(db.Model):

    __tablename__='scents'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(64),nullable = False)
    description = db.Column(db.String(500), nullable = False)
    scent_note1 = db.Column(db.String(20),nullable = False)
    scent_note2 = db.Column(db.String(20),nullable = False)
    scent_note3 = db.Column(db.String(20),nullable = False)

    def __repr__(self):
        str = 'ID: {}, Name: {}, Description: {} \n'
        str = str.format(self.id, self.name, self.description)
        return str

cadenza/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email


#Checkout Form
class CheckoutForm(FlaskForm):
    firstname = StringField("First Name", validators=[InputRequired()])
    lastname = StringField("Last Name", validators=[InputRequired()])
    email = StringField("Your Email")
    phone = StringField("Your Phone Number", validators=[InputRequired()])
    address = StringField("Your address", validators=[InputRequired()])
    city = StringField("Your city", validators=[InputRequired()])
    state = StringField("Your state", validators=[InputRequired()])
    post_code = StringField("Your postcode", validators=[InputRequired()])
    submit = SubmitField("Send to agent")

cadenza/__init__.py
#import flask - from the package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.debug = True
    app.secret_key = 'MySecretKey'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///cadenza.sqlite'

    db.init_app(app)

    Bootstrap(app)

    from . import views
    app.register_blueprint(views.bp)

    @app.errorhandler(404)
    # takes error as parameter
    def not_found(e):
        return render_template("404.html", error=e)

    @app.errorhandler(500)
    # takes error as parameter
    def not_found(e):
        return render_template("500.html", error=e)

    return app 

cadenza/views.py
from flask import Blueprint, render_template, request, session, flash, redirect, url_for
from . import db
from .models import Product, Scent, Order
from datetime import datetime

bp = Blueprint('main', __name__)



@bp.route('/')
def index():
    products = Product.query.order_by(Product.id).all()
    scents = Scent.query.order_by(Scent.id).all()
    return render_template('index.html', products = products, scents = scents, category = 'All products')




@bp.route('/all_products')
def all_products():
    products = Product.query.order_by(Product.id).all()
    scents = Scent.query.order_by(Scent.id).all()
    return render_template('shop.html', products = products, scents = scents, category = 'All products')




@bp.route('/candles')
def candles():
    products = Product.query.filter_by(category='Candle').order_by(Product.id).all()
    scents = Scent.query.order_by(Scent.id).all()
    return render_template('shop.html', products = products, scents = scents, category = 'Candles')




@bp.route('/colognes')
def colognes():
    products = Product.query.filter_by(category='Cologne').order_by(Product.id).all()
    scents = Scent.query.order_by(Scent.id).all()
    return render_template('shop.html', products = products, scents = scents, category = 'Colognes')




@bp.route('/basket', methods=['POST', 'GET'])
def basket():
    product_id = request.values.get('product_id')

    # get an order if one is in progress
    if 'session_id' in session.keys():
        order = Order.query.get(session['session_id'])
    else:
        order = None

    print(order)
    # create new order if none present
    if order is None:
        order =Order(payment_status = False, date=datetime.now(), first_name='', last_name='', email='', phone='', address='', city='', state='', post_code='')
     
        db.session.add(order)
        db.session.commit()
        session['session_id'] = order.id

    
    # calcs total price 
    total_price = 0
    if order is not None:
        for product in order.products:
            total_price = total_price + product.price

    # checks for adding an item
    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        print(product)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.basket'))
        else:
            flash('Item already in basket!')
            return redirect(url_for('main.basket'))

    
    return render_template('basket.html', order = order, total_price = total_price)


# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'session_id' in session:
        order = Order.query.get_or_404(session['session_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.basket'))
        except sqlalchemy.orm.exc.UnmappedInstanceError as e:
            return f'Problem deleting item from order: {str(e)}'
    return redirect(url_for('main.basket'))


@bp.route('/checkout')
def checkout():
    order = Order.query.get(session['session_id'])

    total_price = 0
    if order is not None:
        for product in order.products:
            total_price = total_price + product.price

    return render_template('checkout.html', total_price = total_price)




@bp.route('/product/<int:product_id>')
def product(product_id):

    selected_product = Product.query.filter_by(id=product_id).first()
    scent_notes = [selected_product.scent.scent_note1, selected_product.scent.scent_note2, selected_product.scent.scent_note3]

    products = Product.query.order_by(Product.id).all()

    product_usage_estimate = ''
    measure = ''

    if selected_product.category == "Candle":
        product_usage_estimate = 'APPROXIMATELY 80 HOUR BURN TIME'
        measure = 'g'
    else:
        product_usage_estimate = 'APPROXIMATELY 300 WEARS'
        measure = 'ml'

    related_products = []

    for product in products:
        if product.category == selected_product.category and product.id != selected_product.id:
            related_products.append(product)

    return render_template('product.html', selected_product = selected_product, related_products = related_products, product_usage_estimate = product_usage_estimate, measure = measure, scent_notes = scent_notes)

cadenza/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
    
    <!-- Fonts -->
    <link rel="stylesheet" href="https://use.typekit.net/nxb7hgm.css">

    <!-- Icons 
    <img width="48" height="48" src="https://img.icons8.com/fluency-systems-regular/48/add-to-basket.png" alt="add-to-basket"/>
    <img width="24" height="24" src="https://img.icons8.com/fluency-systems-regular/48/shopping-basket-2.png" alt="shopping-basket-2"/>
    -->
    
    <title>Cadenza Fragrances</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    
  </head>

  <body>

    <header>
        <nav class="navbar navbar-expand-lg fixed-top border-bottom navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">CADENZA</a>

            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item px-3 active grow-less">
                  <a class="nav-link" href="{{ url_for('main.all_products') }}">SHOP<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item px-3 grow-less">
                  <a class="nav-link" href="#">OUR STORY</a>
                </li>
                <li class="nav-item px-3 grow-less">
                    <a class="nav-link" href="#">CONTACT US</a>
                  </li>
              </ul>
            </div>

            
            <ul class="navbar-nav ml-auto nav-stick-cart">
                <li class="nav-item">
                    <a href="{{ url_for('main.basket') }}" class="btn grow"><img width="24" height="24" src="https://img.icons8.com/fluency-systems-regular/48/shopping-basket-2.png" alt="shopping-basket-2"/></a>
                </li>
            </ul>

            <button class="navbar-toggler nav-stick-toggle grow" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </nav>

        {% block head %}{% endblock %}

    </header>

    
    <!-- Main Page content goes here-->
    <main>
    {% block main %}
    {% endblock %}
      

      <!-- Reccomendation -->
      <div class="overflow-container-1 prodcut-spacing {
        margin-top: 100px !important;}">
        <div class="overlay-content">
          <h6>Having trouble deciding?</h6>
          <h2>
            Reach out to us for our personalised reccomendations
          </h2>
          <button type="button" class="btn btn-primary-vanilla grow-less">REACH OUT</button>
        </div>
        <img src="{{ url_for('static', filename='img/quiz_image.jpeg')}}" class="img-fluid" alt="Responsive image">
        <div class="overlay"></div>
      </div>

    </main>

    <!--Footer-->
      <footer class="bg-light text-center text-lg-start">
        <div class="container-fluid text-center pt-5 pb-5">
            <div class="row">
              <h5 class="col text-left">
                <b>Shop 4, 82 Hensley Avenue<br/>
                Brisbane</b>
              </h5>
              <div class="col">
                <img src="/static/img/instagram.png" class="img-fluid" alt="Responsive image" style="width: 24px; height: 24pxpx; margin:0 auto;">
              </div>
              <h5 class="col text-right">
                <b>reachout@cadenza.com.au<br/></b>
                1800 768 554
              </h5>
            </div>
          </div>
        
        <div class="copyright pb-5">
            <h5>
                © 2023 Copyright: Cadenza
            </h5>
        </div> 
      </footer>
    <!--Footer-->
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      
</body>
</html>

cadenza/templates/basket.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block main %}
<section>
    <div class="hero-spacer" >
        <img src="{{ url_for('static', filename='img/quiz_image.jpeg')}}" class="card-img-top hero-spacer-img" alt="Card Image">
    </div>
    <div class="container">
        <div class="row co-12 d-flex mt-5 mb-5">
            <h3>Your Cart</h3>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% for item in order.products %}
                <div class="row shadow-md my-row mb-3">
                    <div class="col-sm-12 card justify-content-between">
                        <h4 class="card-header basket-header">{{ item.name }} : {{ item.category }}
                            <form method="post" class="product-page-add-to-cart float-right" action="{{ url_for('main.deleteorderitem') }}">
                                <input type="hidden" id="id" name="id" value="{{ item.id }}">
                                <button class="remove" type="submit">
                                    <div class="float-right">Delete</div>
                                </button>
                            </form>
                            
                        </h4>
                        <div class="row">
                            <div class="col-4">
                                <img class="img-thumbnail" src="{{url_for('static', filename='img/' + item.image_url)}}">
                            </div>
                            <div class="col-8">
                                <div class="d-flex flex-column justify-content-between align-items-end h-100">
                                    <div>
                                    </div>
                                    <div>
                                        <h5 class="basket-price">{{ "${:,.2f}".format(item.price) }}</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <h4 class="card-header basket-header"><a4>Total Price</a4></h4>
                    <div class="card-body ">
                        <div class="justify-content-between">
                            <h4 class="card-text basket-header">Subtotal:
                                <a class="float-right basket-header">{{ "${:,.2f}".format(total_price * 0.90) }}</a>
                            </h4>
                        </div>
                        <div class="justify-content-between">
                            <h4 class="card-text basket-header">GST:
                                <a class="float-right basket-header">{{ "${:,.2f}".format(total_price * 0.10) }}</a>

                            </h4>
                        </div>
                        <div class="justify-content-between mt-3">
                            <h4 class="card-text basket-price basket-header">Total:
                                <a class="float-right ">{{ "${:,.2f}".format(total_price) }}</a>
                            </h4>
                        </div>
                        <a href="{{ url_for('main.checkout') }}">
                            <button type="button" class="slide btn-cart btn-outline-cart mt-5">Check Out</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

cadenza/templates/index.html
{% extends 'base.html' %}

{% block main %}
<!-- Hero Section -->
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/static/img/hero.jpeg" class="d-block w-100 image-dim-1" alt="...">
      <div class="carousel-caption h-50">
        <h6>Welcome home</h6>
        <h2>Define your space with our new candle collection</h2>
        <a href="{{ url_for('main.candles') }}"><button type="button" class="btn btn-primary-vanilla grow-less">SHOP NOW</button></a>
        
      </div>
    </div>
    <div class="carousel-item">
      <img src="/static/img/hero_2.jpeg" class="d-block w-100 image-dim-2" alt="...">
      <div class="carousel-caption h-50">
        <h6>Find your signature scent</h6>
        <h2>our new cologne range is yours to explore</h2>
        <a href="{{ url_for('main.colognes') }}"><button type="button" class="btn btn-primary-vanilla grow-less">SHOP NOW</button></a>
        
      </div>
    </div>
  </div>
</div>

<!-- Sub-Hero Section -->
<div class="sub-hero">
  <div class="col-sm-12 d-flex justify-content-center">
      <h3>Journey into Fragrant Opulence</h3>
  </div>
  <div class="col-sm-12 d-flex justify-content-center mt-3">
      <div class="sub-hero-message">Explore a world of timeless elegance and enchanting scents that define luxury, as we invite you to experience the allure of our meticulously crafted fragrances, where every drop is a masterpiece.</div>
  </div>
</div>

<!-- Product Nav -->
<div class="stick-on-scroll">
  <div style="width: 100%; height: 65px; background-color: transparent;"></div>
  <div class="category-row">
    <div class="row ">
        <div class="col-sm-4 d-flex justify-content-center align-self-center">
          <a href="{{ url_for('main.candles') }}" class="product-category white-font grow-less scroll-link">Candles</a>
        </div>
        <div class="col-sm-4 d-flex justify-content-center">
          <a href="{{ url_for('main.all_products') }}" class="product-category white-font grow-less scroll-link">All Products</a>
        </div>
        <div class="col-sm-4 d-flex justify-content-center">
          <a href="{{ url_for('main.colognes') }}" class="product-category white-font grow-less scroll-link">Colognes</a>
        </div>
    </div>
  </div>
  <div class="dropdown d-flex justify-content-center filter-toggle">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
       Filter Scents
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
       {% for scent in scents %}
         <li><a class="dropdown-item" href="#">{{ scent.name }}</a></li>
       {% endfor %}
    </ul>
   </div>
</div>



<!-- Display Products -->
<div class="container-fluid">
  <div class="row">
    {% for product in products %}
    <div class="col">
      <div class="card mt-5 mb-5" style="width: 18rem;">
        <a href="{{ url_for('main.product', product_id=product.id) }}">
          <img src="{{ url_for('static', filename='img/' + product.image_url) }}" class="card-img-top" alt="Card Image">
        </a>
        <div class="card-body">
          <div class="product-title-cart d-flex justify-content-between">
            <a href="{{ url_for('main.product', product_id=product.id) }}"><h4 class="product-name">{{ product.name }}</h4></a>
            <div>
              <form class="product-page-add-to-cart" action="{{ url_for('main.basket') }}">
                <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                <button class="remove" type="submit">
                  <img class="align-right grow" width="24" height="24" src="https://img.icons8.com/fluency-systems-regular/48/add-to-basket.png" alt="add-to-basket">
              </button>
            </form>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h5 class="card-title">{{ product.scent.name }}</h5>
            </div>
            <div class="col">
              <h5 class="card-title text-right">{{ "${:,.2f}".format(product.price) }}</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %} 

cadenza/templates/product.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block main %}
<!-- Product Info -->

<div class="container-fluid text-center mt-5 mb-5 pt-5">
    <div class="row">
      <div class="col-lg-8">
        <img src="{{url_for('static', filename='img/'+selected_product.image_url) }}" class="card-img-top" alt="...">
      </div>
      <div class="col-lg-4">
        <div class="card-body">
          <h4 class="card-title text-left" style="font-weight: 300;">{{ selected_product.name }}</h4>
          <div>
            <h5 class="card-title text-left" style="font-size: 24px; color:grey;">{{ "${:,.2f}".format(selected_product.price) }}</h5>
          </div>
          <hr/>
          <div class="card-title text-left mt-5 product-detail-titles">{{ selected_product.sub_headline }}</div>
          <p class="card-text text-left mt-3">{{ selected_product.description }}<br/><br/>{{ selected_product.scent.description }}</p>
          <div class="card-title text-left mt-5 product-detail-titles">Scent Notes</div>
          <ul>
            {% for scent_note in scent_notes %}
            <li class="text-left scent-list-text">{{ scent_note }}</li>
            {% endfor %}
          </ul>
          <div class="card-title text-left mt-5 product-size-details">{{ selected_product.size }}{{ measure }} | {{ product_usage_estimate }}</div>
          <div>
            <form class="product-page-add-to-cart" action="{{ url_for('main.basket') }}">
                <input type="hidden" id="product_id" name="product_id" value="{{ selected_product.id }}">
                <button href="" type="submit" class="slide btn-cart btn-outline-cart mt-5">Add to Cart</button>
            </form>
        </div>
          
        </div>
      </div>
    </div>
  </div>

  <!-- Related Products -->
  <div class="related-title related-prodcut-spacing text-center mb-5 pt-5">Related Products</div>

  <div class="container-fluid mx-auto mt-5 ">
    <div class="row justify-content-between left-push">
      {% for product in related_products %}
      <div class="col-12 col-md-4">
        <div class="card" style="width: 18rem;">
          <a href="{{ url_for('main.product', product_id=product.id) }}"><img src="{{ url_for('static', filename='img/' + product.image_url) }}" class="card-img-top" alt="Card Image"></a>
          <div class="card-body">
            <div class="product-title-cart">
              <a href="{{ product.link }}"><h4 class="card-title">{{ product.name }}</h4></a>
            </div>
            <h5 class="card-title">{{ product.scent_id.name }}</h5>
            <h5 class="card-title">{{ "${:,.2f}".format(product.price) }}</h5>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  

{% endblock %}

cadenza/templates/shop.html
{% extends 'base.html' %}

{% block main %}
<!-- Product Nav -->
<div class="stick-on-scroll">
  <div style="width: 100%; height: 65px; background-color: transparent;"></div>
  <div class="category-row">
    <div class="row ">
        <div class="col-sm-4 d-flex justify-content-center align-self-center">
          <a href="{{ url_for('main.candles') }}" class="product-category white-font grow-less scroll-link">Candles</a>
        </div>
        <div class="col-sm-4 d-flex justify-content-center">
          <a href="{{ url_for('main.all_products') }}" class="product-category white-font grow-less scroll-link">All Products</a>
        </div>
        <div class="col-sm-4 d-flex justify-content-center">
          <a href="{{ url_for('main.colognes') }}" class="product-category white-font grow-less scroll-link">Colognes</a>
        </div>
    </div>
  </div>
  <div class="dropdown d-flex justify-content-center filter-toggle">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
       Filter Scents
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
       {% for scent in scents %}
         <li><a class="dropdown-item" href="#">{{ scent.name }}</a></li>
       {% endfor %}
    </ul>
   </div>
</div>



<!-- Display Prodcuts -->
<div class="container-fluid mt-5">
  <div class="row">
    {% for product in products %}
    <div class="col">
      <div class="card mt-5 mb-5" style="width: 18rem;">
        <a href="{{ url_for('main.product', product_id=product.id) }}">
          <img src="{{ url_for('static', filename='img/' + product.image_url) }}" class="card-img-top" alt="Card Image">
        </a>
        <div class="card-body">
          <div class="product-title-cart d-flex justify-content-between">
            <a href="{{ url_for('main.product', product_id=product.id) }}"><h4 class="product-name">{{ product.name }}</h4></a>
            <div>
              <form class="product-page-add-to-cart" action="{{ url_for('main.basket') }}">
                <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                <button class="remove" type="submit">
                  <img class="align-right grow" width="24" height="24" src="https://img.icons8.com/fluency-systems-regular/48/add-to-basket.png" alt="add-to-basket">
              </button>
            </form>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h5 class="card-title">{{ product.scent.name }}</h5>
            </div>
            <div class="col">
              <h5 class="card-title text-right">{{ "${:,.2f}".format(product.price) }}</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %} 